# Generated by Django 4.2.3 on 2025-06-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto", models.CharField(max_length=40)),
                ("marca", models.CharField(max_length=40)),
                ("valor", models.FloatField()),
                ("quantidade", models.IntegerField()),
            ],
        ),
    ]
