# Generated by Django 4.2.3 on 2025-06-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0002_pedido"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="usuario",
        ),
        migrations.AddField(
            model_name="pedido",
            name="cliente",
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
